Repository ZenBit-Tech/ZenBitRock_be, pull requests merged in 2023-12, with the labels that each got.

#16 feat(dto): add db fields
  src/common/entities/user.entity.ts
  src/modules/verification/dto/create-verification.dto.ts
Labels: enhancement

#18 feat: add update user data controller
  src/modules/user/dto/update-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: enhancement

#20 chore: add fields to user details response
  src/common/entities/user.entity.ts
  src/common/types/user-profile-response.type.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/user/dto/update-user.dto.ts
Labels: enhancement

#22 chore: add type
  src/common/types/index.ts
  src/common/types/user-info-response.ts
  src/common/types/user-profile-response.type.ts
  src/modules/auth/strategies/jwt.strategy.ts
Labels: enhancement

#24 fix: added qobrix secret keys to headers middleware
  src/common/configs/dto/config.dto.ts
  src/middleware/qobrix.middleware.ts
Labels: enhancement

#25 zb-5: change verify email return type
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: enhancement

#27 zb-6: change login return type
  src/common/types/index.ts
  src/common/types/user-sign-in-response.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: bug

#26 fix(register): add corrections to error handling
  .env.example
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: enhancement

#28 feat: added delete avarar endpoint
  .env.example
  src/app.module.ts
  src/common/entities/user.entity.ts
  src/common/types/user-info-response.ts
  src/middleware/qobrix.middleware.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/cloudinary/cloudinary.service.ts
  src/modules/cloudinary/dto/uploaded-file.dto.ts
  src/modules/user/dto/delete-avatar.dto.ts
  src/modules/user/dto/set-avatar.dto.ts
  src/modules/user/dto/update-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
  src/modules/verification/dto/create-verification.dto.ts
  src/modules/verification/dto/upload-file.dto.ts
  src/modules/verification/verification.service.ts
Labels: enhancement

#29 feat(api): add delete from crm functionality
  .env.example
  package-lock.json
  package.json
  src/common/configs/dto/config.dto.ts
  src/modules/http/http.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.ts
Labels: enhancement

#30 Task/zb 6 add leads module
  src/app.module.ts
  src/common/enums/index.ts
  src/common/enums/qobrix-api-path.enum.ts
  src/common/types/index.ts
  src/common/types/lead/contact.type.ts
  src/common/types/lead/index.ts
  src/common/types/lead/lead-details-response.type.ts
  src/common/types/lead/lead.type.ts
  src/common/types/lead/workflow-stage.type.ts
  src/common/types/property/index.ts
  src/common/types/property/matching-properties-response.type.ts
  src/common/types/property/property-type.ts
  src/modules/lead/lead.controller.ts
  src/modules/lead/lead.module.ts
  src/modules/lead/lead.service.ts
  src/modules/lead/lib/enums/index.ts
  src/modules/lead/lib/enums/opportunity-buy-rent.enum.ts
  src/modules/lead/lib/enums/property-sale-rent.enum.ts
  src/modules/lead/lib/helpers/getBathroomsFilter.ts
  src/modules/lead/lib/helpers/getPropertySearchFilter.ts
  src/modules/lead/lib/helpers/getSellingPriceFilter.ts
  src/modules/lead/lib/helpers/index.ts
  src/modules/lead/lib/index.ts
Labels: enhancement

#32 zb-7: add matching properties
  src/common/configs/config.service.ts
  src/common/configs/database/database-config.ts
  src/common/configs/database/typeorm-config.ts
  src/common/entities/core.entity.ts
  src/common/types/lead/lead-details-response.type.ts
  src/common/types/property/matching-properties-response.type.ts
  src/common/types/user-info-response.ts
  src/main.ts
  src/middleware/qobrix.middleware.ts
  src/modules/auth/dto/change-password.dto.ts
  src/modules/auth/dto/verify-password.dto.ts
  src/modules/cloudinary/cloudinary.module.ts
  src/modules/cloudinary/cloudinary.service.ts
  src/modules/email/email.controller.ts
  src/modules/http/http.service.ts
  src/modules/lead/lead.controller.ts
  src/modules/lead/lead.service.ts
  src/modules/lead/lib/helpers/getBathroomsFilter.ts
  src/modules/lead/lib/helpers/getPropertySearchFilter.ts
  src/modules/lead/lib/helpers/getSellingPriceFilter.ts
  src/modules/lead/lib/helpers/index.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
  src/modules/verification/verification.controller.ts
  src/modules/verification/verification.module.ts
  src/modules/verification/verification.service.ts
Labels: enhancement

#33 zb-8: add avatar refresh after change
  src/common/types/index.ts
  src/common/types/user/index.ts
  src/common/types/user/user-set-avatar-response.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: enhancement

#35 zb:-9: add socket connection
  package-lock.json
  package.json
  src/app.module.ts
  src/common/types/index.ts
  src/common/types/socket/index.ts
  src/common/types/socket/socket-with-auth.type.ts
  src/common/types/socket/token-payload-type.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
Labels: enhancement

#34 fix: update swagger documentation
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/auth.dto.ts
  src/modules/user/dto/create-user.dto.ts
  src/modules/user/user.controller.ts
Labels: documentation

#36 feat: create main chat logic
  src/app.module.ts
  src/common/entities/message.entity.ts
  src/common/entities/room.entity.ts
  src/common/entities/user.entity.ts
  src/main.ts
  src/modules/message/dto/create-message.dto.ts
  src/modules/message/dto/get-messages.dto.ts
  src/modules/message/message.controller.ts
  src/modules/message/message.module.ts
  src/modules/message/message.service.ts
  src/modules/room/dto/create-room.dto.ts
  src/modules/room/dto/get-rooms.dto.ts
  src/modules/room/dto/search-room.dto.ts
  src/modules/room/room.controller.ts
  src/modules/room/room.module.ts
  src/modules/room/room.service.ts
Labels: good first issue
